# Generated by Django 6.0.2 on 2026-02-11 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'ordering': ['-date_requested'], 'verbose_name': 'Claim Request', 'verbose_name_plural': 'Claim Requests'},
        ),
        migrations.AlterModelOptions(
            name='founditem',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Found Item', 'verbose_name_plural': 'Found Items'},
        ),
        migrations.AlterModelOptions(
            name='lostitem',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Lost Item', 'verbose_name_plural': 'Lost Items'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name or class', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='description',
            field=models.TextField(help_text='Description of why this item belongs to you'),
        ),
        migrations.AlterField(
            model_name='founditem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='found_items', to='items.category'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_items', to='items.category'),
        ),
        migrations.AlterUniqueTogether(
            name='claimrequest',
            unique_together={('item', 'claimant')},
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['status'], name='items_claim_status_0f5242_idx'),
        ),
        migrations.AddIndex(
            model_name='claimrequest',
            index=models.Index(fields=['date_requested'], name='items_claim_date_re_0a65d6_idx'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['status'], name='items_found_status_59ebe1_idx'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['found_date'], name='items_found_found_d_6b38d7_idx'),
        ),
        migrations.AddIndex(
            model_name='founditem',
            index=models.Index(fields=['user', 'status'], name='items_found_user_id_ef1d44_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['status'], name='items_losti_status_d995db_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['lost_date'], name='items_losti_lost_da_eed94f_idx'),
        ),
        migrations.AddIndex(
            model_name='lostitem',
            index=models.Index(fields=['user', 'status'], name='items_losti_user_id_1aa83b_idx'),
        ),
    ]
