# Generated by Django 6.0.2 on 2026-02-28 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='claimrequest',
            name='items_claim_status_0f5242_idx',
        ),
        migrations.RemoveIndex(
            model_name='claimrequest',
            name='items_claim_date_re_0a65d6_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='items_notif_user_id_88fa71_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='items_notif_user_id_7f937a_idx',
        ),
        migrations.RenameField(
            model_name='claimrequest',
            old_name='date_requested',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='claimrequest',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='additional_info',
            field=models.TextField(blank=True, help_text='Any additional proof or information'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection (if rejected)'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.claimrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_id',
            field=models.IntegerField(blank=True, help_text='ID of related object', null=True),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='description',
            field=models.TextField(help_text='Describe why this item belongs to you'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Claim Accepted'), ('rejected', 'Claim Rejected'), ('withdrawn', 'Claim Withdrawn')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('claim', 'New Claim'), ('claim_accepted', 'Claim Accepted'), ('claim_rejected', 'Claim Rejected'), ('claim_withdrawn', 'Claim Withdrawn'), ('item_found', 'Item Found'), ('item_matched', 'Item Matched')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='found_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='lost_item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='updated_at',
        ),
    ]
